name: 3dgan_tf2
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - blas=1.0=mkl
  - ca-certificates=2020.12.5=ha878542_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - certifi=2020.12.5=py38h578d9bd_1
  - cudatoolkit=11.0.221=h6bb024c_0
  - freetype=2.10.4=h5ab3b9f_0
  - hdf5=1.10.6=nompi_h3c11f04_101
  - intel-openmp=2020.2=254
  - jpeg=9b=h024ee3a_2
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_1
  - lz4-c=1.9.3=h2531618_0
  - mkl=2020.2=256
  - mkl-service=2.3.0=py38he904b0f_0
  - mkl_fft=1.3.0=py38h54f3939_0
  - mkl_random=1.1.1=py38h0573a6f_0
  - ncurses=6.2=he6710b0_1
  - nibabel=3.2.1=pyhd8ed1ab_0
  - numpy-base=1.19.2=py38hfa32c7d_0
  - olefile=0.46=py_0
  - openssl=1.1.1k=h27cfd23_0
  - packaging=20.9=pyh44b312d_0
  - pillow=8.2.0=py38he98fc37_0
  - pip=21.0.1=py38h06a4308_0
  - pydicom=2.1.2=pyhd3deb0d_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - python=3.8.8=hdb3f193_4
  - python_abi=3.8=1_cp38
  - readline=8.1=h27cfd23_0
  - scipy=1.6.2=py38h91f5cce_0
  - setuptools=52.0.0=py38h06a4308_0
  - six=1.15.0=py38h06a4308_0
  - sqlite=3.35.4=hdfb4753_0
  - tk=8.6.10=hbc83047_0
  - tqdm=4.59.0=pyhd3eb1b0_1
  - tzdata=2020f=h52ac0ba_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.9=haebb681_0
  - pip:
    - absl-py==0.12.0
    - astunparse==1.6.3
    - cachetools==4.2.1
    - chardet==4.0.0
    - flatbuffers==1.12
    - gast==0.3.3
    - google-auth==1.28.1
    - google-auth-oauthlib==0.4.4
    - google-pasta==0.2.0
    - grpcio==1.32.0
    - h5py==2.10.0
    - idna==2.10
    - keras-preprocessing==1.1.2
    - markdown==3.3.4
    - numpy==1.19.5
    - oauthlib==3.1.0
    - opt-einsum==3.3.0
    - protobuf==3.15.8
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - requests==2.25.1
    - requests-oauthlib==1.3.0
    - rsa==4.7.2
    - tensorboard==2.4.1
    - tensorboard-plugin-wit==1.8.0
    - tensorflow==2.4.0
    - tensorflow-estimator==2.4.0
    - termcolor==1.1.0
    - typing-extensions==3.7.4.3
    - urllib3==1.26.4
    - werkzeug==1.0.1
    - wrapt==1.12.1
prefix: /data/vision/polina/users/razvan/sungmin/Installer/Anaconda/anaconda3/envs/3dgan_tf2
